#!/bin/sh

window=0

while getopts w flag
do
    case "${flag}" in
        w) window=1;;
    esac
done


if [ $window -eq 1 ]
then
    tmux split-window -h 'R'
    tmux split-window -v
    cd ~/work/ucl/
    tmux select-pane -t 0
    vim
fi

if [ $window -eq 0 ]
then
    tmux new-session -d 'vim'
    tmux split-window -h 'R'
    tmux split-window -v
    tmux new-window 'mutt'
    tmux -2 attach-session -d
    cd ~/work/ucl/
    tmux select-pane -t 0
fi



